controller_list:
  - name: fake_leg1_controller
    type: $(arg fake_execution_type)
    joints:
      - leg1_joint1
      - leg1_joint2
      - leg1_joint3
  - name: fake_leg2_controller
    type: $(arg fake_execution_type)
    joints:
      - leg2_joint1
      - leg2_joint2
      - leg2_joint3
  - name: fake_leg3_controller
    type: $(arg fake_execution_type)
    joints:
      - leg3_joint1
      - leg3_joint2
      - leg3_joint3
  - name: fake_leg4_controller
    type: $(arg fake_execution_type)
    joints:
      - leg4_joint1
      - leg4_joint2
      - leg4_joint3
  - name: fake_leg5_controller
    type: $(arg fake_execution_type)
    joints:
      - leg5_joint1
      - leg5_joint2
      - leg5_joint3
  - name: fake_leg6_controller
    type: $(arg fake_execution_type)
    joints:
      - leg6_joint1
      - leg6_joint2
      - leg6_joint3
initial:  # Define initial robot poses per group
#  - group: leg1
#    pose: home

  []