leg1_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - leg1_joint1
    - leg1_joint2
    - leg1_joint3
  gains:
    leg1_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg1_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg1_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1